-- MATHORA DATABASE SETUP
-- Run in Supabase SQL Editor.
-- This script is safe to run again.

create extension if not exists pgcrypto;

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  full_name text not null,
  email text not null,
  phone text not null,
  year_group text not null,
  qualification text not null,
  exam_board text not null,
  level text not null,
  current_grade text,
  target_grade text not null,
  notes text,
  status text not null default 'submitted'
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  attempt_id uuid not null references public.attempts(id) on delete cascade,
  question_number integer not null check (question_number between 1 and 12),
  topic text not null,
  question_text text not null,
  maximum_marks integer not null,
  final_answer text
);

create table if not exists public.submission_files (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  attempt_id uuid not null references public.attempts(id) on delete cascade,
  question_number integer not null check (question_number between 1 and 12),
  file_type text not null check (file_type in ('uploaded_working','whiteboard')),
  storage_path text not null
);

alter table public.attempts enable row level security;
alter table public.answers enable row level security;
alter table public.submission_files enable row level security;

drop policy if exists "Allow anonymous assessment inserts" on public.attempts;
create policy "Allow anonymous assessment inserts"
on public.attempts for insert to anon with check (true);

drop policy if exists "Allow anonymous answer inserts" on public.answers;
create policy "Allow anonymous answer inserts"
on public.answers for insert to anon with check (true);

drop policy if exists "Allow anonymous file record inserts" on public.submission_files;
create policy "Allow anonymous file record inserts"
on public.submission_files for insert to anon with check (true);

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'mathora-workings',
  'mathora-workings',
  false,
  6291456,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Allow anonymous working uploads" on storage.objects;
create policy "Allow anonymous working uploads"
on storage.objects for insert to anon
with check (bucket_id='mathora-workings');

drop policy if exists "Allow anonymous upload replacement" on storage.objects;
create policy "Allow anonymous upload replacement"
on storage.objects for update to anon
using (bucket_id='mathora-workings')
with check (bucket_id='mathora-workings');
